# docker-compose.yml
services:
  mysql:
    container_name: esg-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - /home/db/mysql/data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      TZ: "Asia/Seoul"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esg
      MYSQL_USER: test1234
      MYSQL_PASSWORD: test1234
    healthcheck: # MySQL 서비스 상태 확인
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - spring-net

  server:
    build: # 디렉토리에 있는 도커파일 이용해서 이미지 빌드
      context: .
      dockerfile: Dockerfile
    container_name: esg-spring-server
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ~/.gradle:/root/.gradle
    command: ./gradlew :application:bootRun
    networks:
      - spring-net


networks:
  spring-net:
    driver: bridge